### ISSUE TITLE
This gotta be a shitpost

### ISSUE THREAD

**Issue by msr8** [blackhatethicalhacking/DDoS-Layer7-bheh#9]
........right?

**Comment by blackhatethicalhacking** [comment]
Its shit if u dont know how to run in python2, if u do know how to run it in python2, then its not shit, and its the user's issue, get it? otherwise feel free to convert it from python2 to python3

**Comment by msr8** [comment]
You're either in your skiddie phase or a top tier troll 😂
![Screenshot 2022-05-18 at 19 08 33](https://user-images.githubusercontent.com/79649185/169052321-a29113eb-cb49-4bba-aa84-67701d654712.png)
This "DDoS method" is not effective AT ALL and is sooo basic and easy to counter..............
![Screenshot 2022-05-18 at 19 09 53](https://user-images.githubusercontent.com/79649185/169052593-2500cf3b-feff-4129-88cc-61aa9bed1db5.png)

**Comment by iloveyumyumshrimpnoodles** [comment]
> So easy to counter, if u have countermeasures.. we still use it, and it still works, just use hping3 bra.. what are u trying to state?

probably that it's not an advanced tool, and only teaches about really basic script kiddie level attacks, which are VERY easy to block.

Perhaps start digging into some more advanced techniques, instead of using the all-public "figlet" attack and some basic `socket.sendto()`'s

Cool tool nonetheless

**Comment by blackhatethicalhacking** [comment]
Basic Script Kiddie? We get that a lot.

**Comment by blackhatethicalhacking** [comment]
It offers over 7 layers of attacks, and it has been updated to simulate them. You judge a lot though, script kiddie, pasted over github 5 years ago? then converted to python 3? Yup, we get u, dude we get also the thousands of clones too.

**Comment by iloveyumyumshrimpnoodles** [comment]
> It offers over 7 layers of attacks, and it has been updated to simulate them. You judge a lot though, script kiddie, pasted over github 5 years ago? then converted to python 3? Yup, we get u, dude we get also the thousands of clones too.

It only contains 2 layer 4 attacks, and a simple HTTP GET flood.
Those attacks used to be common, but are a lot less nowadays.

If you'd want to simulate an actual attack, i would suggest looking into dynamic attacks which spoof headers and GET parameters. Those attacks are much more common than simple plain `GET /` floods.

As for the SYN flood, it has been patched so trying to use it nowadays is like trying to shoot a tank with a 9mm. It might do a bit of damage but won't do anything on the long term.
I am currently writing an entire toolkit of layer 2, 3, 4 and 7 attack methods/vectors, which will include these types of attacks next to the other ones you included.

This serves as a much more "battle-ready" tool, rather than some attacks which were relevant 5 years ago.

Again, like i said i get the low-entry thing, because you're a programmer which is focused on learning and providing an easy entry for lesser-experienced programmer (i'd guess, from your github profile) so i totally get the pasted attacks.

Also, i didn't call you a script kiddie, did i?

**Comment by blackhatethicalhacking** [comment]
I mean listen i get it, all that - i know i wrote the tool, its also the machines running these types of flooding attacks, but also you could add to this script, and basically perform zombie and gather other iot devices, and make an ultimate way of sending packets, if you wanna bypass these, you can - this was written 5 years ago dude, do u know why types of security devices were then and now? and still - we get ur feedback, but if u have an issue with running the tool, we happy to solve it, if u wanna give an opinion, you can do it in discussion - i am not a programmer though. find out about us a bit more, and pasting and judging we get ur opinion, but we know - what we write and what we do, we accept opinions and decide what is good to take or not ya feel me? Thanks for u feedback though.
